[package]
name = "cid-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
proxy-wasm = "=0.2.1"

[lib]
name = "cid_generator"
crate-type = ["cdylib"]
